spring:
  application:
    name: backend

  datasource:
    url: jdbc:h2:mem:backdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 3600000
  refresh-token-expiry: 604800000

app:
  frontend-url: http://localhost:3000  # 나중에 수정